### ISSUE TITLE
Switching modes inside a component's CSS is possible

### ISSUE THREAD

**Issue by acstll** [telekom/design-tokens#3]
Via the [`:host-context()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context()) pseudo-class selector.

```css
:host-context(body[data-mode="dark"]) .modal__window {
  background: rosybrown;
}
```
